# GitHub actions workflow which builds and publishes the docker images.

name: Build docker images

on:
  push:
    tags: ["v*"]
    branches: [ master, main, develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: docker buildx inspect

      # copy from https://github.com/matrix-org/synapse/blob/96e0cdbc5af0563ee805ec4e588e1df14899af66/.github/workflows/docker.yml#L39-L56
      - name: Calculate docker image tag old
        id: set-tag-old
        run: |
          case "${GITHUB_REF}" in
              refs/heads/develop)
                  tag=develop
                  ;;
              refs/heads/master|refs/heads/main)
                  tag=latest
                  ;;
              refs/tags/*)
                  tag=${GITHUB_REF#refs/tags/}
                  ;;
              *)
                  tag=${GITHUB_SHA}
                  ;;
          esac
          echo "::set-output name=tag::$tag"

      # copy from https://github.com/henryclw/synapse/blob/57f4421ceb2d649da75c2e7c46c53220b7350716/.github/workflows/docker.yml#L37-L50
      - name: Calculate docker image tag new
        id: set-tag-new
        uses: docker/metadata-action@master
        with:
          images: matrixdotorg/synapse
          flavor: |
            latest=false
          tags: |
            type=pep440,pattern={{raw}}
            type=raw,value=develop,enable=${{ github.ref == 'refs/heads/develop' }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Echo different output of set-tag
        run: echo "The old set-tag output is  matrixdotorg/synapse:${{ steps.set-tag-old.outputs.tag }} \n The new set-tag output is ${{ steps.set-tag-new.outputs.tags }}"

      - name: Build and run docker container
        run: docker build -t "${{ steps.set-tag-new.outputs.tags }}" . && docker run --name dummy_docker "${{ steps.set-tag-new.outputs.tags }}"
